# .github/workflows/build-and-push-on-main.yml
name: Build and Push Docker Image on Main

on:
  push:
    branches: [ main ]

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: general

    steps:
    - name: Checkout code (read-only)
      uses: actions/checkout@v3
      with:
        persist-credentials: false      # evita credenciales de push

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # VERSION = número de ejecución → v1, v2, v3...
    - name: Set VERSION env
      run: echo "VERSION=${{ github.run_number }}" >> $GITHUB_ENV

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        # si algún día necesitas multi-arch, descomenta:
        # platform: linux/amd64,linux/arm64
        build-args: |
          APP_VERSION=${{ env.VERSION }}
        tags: |
          maximorero14/k8_payment:latest
          maximorero14/k8_payment:v${{ env.VERSION }}